package cli

import (
	"fmt"
	"strings"

	"github.com/arthurlch/goryu/internal/utils"
)

func generateSQLCHandlerContent(name string) string {
	handlerName := utils.ToGoIdentifier(name)
	lowerName := strings.ToLower(name)
	modelName := utils.ToGoIdentifier(name)

	return fmt.Sprintf(`package handlers

import (
	"database/sql"
	"net/http"
	"strconv"

	"github.com/arthurlch/goryu"
	"myapp/internal/database" // generated by sqlc
)

type %sHandler struct {
	q *database.Queries
}

func New%sHandler(db *sql.DB) *%sHandler {
	return &%sHandler{
		q: database.New(db),
	}
}

// RegisterRoutes registers the routes for this handler
func (h *%sHandler) RegisterRoutes(app *goryu.App) {
	group := app.Group("/%s")
	group.GET("/", h.List%ss)
	group.GET("/:id", h.Get%s)
	group.POST("/", h.Create%s)
}

// Get%s handles GET /%s/:id
func (h *%sHandler) Get%s(c *goryu.Context) {
	idStr := c.Param("id")
	id, err := strconv.ParseInt(idStr, 10, 64)
	if err != nil {
		c.JSON(http.StatusBadRequest, map[string]string{"error": "Invalid ID"})
		return
	}

	item, err := h.q.Get%s(c.Context(), id)
	if err == sql.ErrNoRows {
		c.JSON(http.StatusNotFound, map[string]string{"error": "%s not found"})
		return
	}
	if err != nil {
		c.Error(err)
		c.JSON(http.StatusInternalServerError, map[string]string{"error": "Database error"})
		return
	}

	c.JSON(http.StatusOK, item)
}

// List%ss handles GET /%s
func (h *%sHandler) List%ss(c *goryu.Context) {
	items, err := h.q.List%ss(c.Context())
	if err != nil {
		c.Error(err)
		c.JSON(http.StatusInternalServerError, map[string]string{"error": "Database error"})
		return
	}
	c.JSON(http.StatusOK, items)
}

// Create%s handles POST /%s
func (h *%sHandler) Create%s(c *goryu.Context) {
	var params database.Create%sParams
	if err := c.BindJSON(&params); err != nil {
		c.JSON(http.StatusBadRequest, map[string]string{"error": "Invalid JSON"})
		return
	}

	item, err := h.q.Create%s(c.Context(), params)
	if err != nil {
		c.Error(err)
		c.JSON(http.StatusInternalServerError, map[string]string{"error": "Failed to create"})
		return
	}

	c.JSON(http.StatusCreated, item)
}
`, handlerName, handlerName, handlerName, handlerName,
		handlerName, lowerName, modelName, modelName, modelName, // RegisterRoutes args
		modelName, lowerName, handlerName, modelName,
		modelName, modelName,
		modelName, lowerName, handlerName, modelName, modelName,
		modelName, lowerName, handlerName, modelName, modelName,
		modelName)
}

func generateEntHandlerContent(name string) string {
	handlerName := utils.ToGoIdentifier(name)
	lowerName := strings.ToLower(name)
	cName := utils.ToGoIdentifier(name)

	return fmt.Sprintf(`package handlers

import (
	"context"
	"net/http"
	"strconv"

	"github.com/arthurlch/goryu"
	"myapp/ent"
	"myapp/ent/%s"
)

type %sHandler struct {
	client *ent.Client
}

func New%sHandler(client *ent.Client) *%sHandler {
	return &%sHandler{client: client}
}

// RegisterRoutes registers the routes for this handler
func (h *%sHandler) RegisterRoutes(app *goryu.App) {
	group := app.Group("/%s")
	group.GET("/:id", h.Get%s)
	group.POST("/", h.Create%s)
}

// Create%s handles POST /%s
func (h *%sHandler) Create%s(c *goryu.Context) {
	var req struct {
		// Define fields here matching your Ent schema
		Name string `+"`json:\"name\"`"+`
	}
	if err := c.BindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, map[string]string{"error": "Invalid request"})
		return
	}

	item, err := h.client.%s.Create().
		SetName(req.Name).
		Save(c.Context())
	if err != nil {
		c.JSON(http.StatusInternalServerError, map[string]string{"error": err.Error()})
		return
	}

	c.JSON(http.StatusCreated, item)
}

// Get%s handles GET /%s/:id
func (h *%sHandler) Get%s(c *goryu.Context) {
	idStr := c.Param("id")
	id, err := strconv.Atoi(idStr)
	if err != nil {
		c.JSON(http.StatusBadRequest, map[string]string{"error": "Invalid ID"})
		return
	}

	item, err := h.client.%s.Get(c.Context(), id)
	if _, ok := err.(*ent.NotFoundError); ok {
		c.JSON(http.StatusNotFound, map[string]string{"error": "Not found"})
		return
	}
	if err != nil {
		c.JSON(http.StatusInternalServerError, map[string]string{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, item)
}
`, lowerName, handlerName, handlerName, handlerName, handlerName,
		handlerName, lowerName, cName, cName, // RegisterRoutes args
		cName, lowerName, handlerName, cName,
		cName,
		cName, lowerName, handlerName, cName,
		cName)
}

func generateGormHandlerContent(name string) string {
	handlerName := utils.ToGoIdentifier(name)
	lowerName := strings.ToLower(name)

	return fmt.Sprintf(`package handlers

import (
	"net/http"
	"strconv"

	"github.com/arthurlch/goryu"
	"myapp/internal/models"
	"gorm.io/gorm"
)

type %sHandler struct {
	db *gorm.DB
}

func New%sHandler(db *gorm.DB) *%sHandler {
	return &%sHandler{db: db}
}

// RegisterRoutes registers the routes for this handler
func (h *%sHandler) RegisterRoutes(app *goryu.App) {
	group := app.Group("/%s")
	group.GET("/", h.List%s)
	group.POST("/", h.Create%s)
}

// List%s handles GET /%s
func (h *%sHandler) List%s(c *goryu.Context) {
	var items []models.%s
	if result := h.db.Find(&items); result.Error != nil {
		c.JSON(http.StatusInternalServerError, map[string]string{"error": result.Error.Error()})
		return
	}
	c.JSON(http.StatusOK, items)
}

// Create%s handles POST /%s
func (h *%sHandler) Create%s(c *goryu.Context) {
	var item models.%s
	if err := c.BindJSON(&item); err != nil {
		c.JSON(http.StatusBadRequest, map[string]string{"error": "Invalid JSON"})
		return
	}

	if result := h.db.Create(&item); result.Error != nil {
		c.JSON(http.StatusInternalServerError, map[string]string{"error": result.Error.Error()})
		return
	}
	c.JSON(http.StatusCreated, item)
}
`, handlerName, handlerName, handlerName, handlerName,
		handlerName, lowerName, handlerName, handlerName, // RegisterRoutes args
		handlerName, lowerName, handlerName, handlerName, handlerName,
		handlerName, lowerName, handlerName, handlerName, handlerName)
}
